version: '3'

services:
  liquibase:
    image: archimedes
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: archimedes
      DB_SCHEMA: archimedes
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - archimedes-network

  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: archimedes
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - archimedes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d archimedes"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pg-db:
    external: true

networks:
  archimedes-network:
    external: true